/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/VpEwaXVcnD0
 */
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { CommandInput, CommandEmpty, CommandList, Command } from "@/components/ui/command"
import { Button } from "@/components/ui/button"
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"

export function dashmockup() {
  return (
    (<div key="1" className="min-h-screen bg-gray-100 p-8">
      <header className="mb-6">
        <h1 className="text-3xl font-semibold">Welcome to your Dashboard</h1>
        <p className="text-sm text-gray-600">Logged in as demo@account.com</p>
      </header>
      <div className="flex flex-col md:flex-row gap-4 mb-6">
        <Select className="max-w-xs md:max-w-[140px]">
          <SelectTrigger className="max-w-[120px]">
            <SelectValue placeholder="All Seasons" />
          </SelectTrigger>
          <SelectContent position="popper">
            <SelectItem value="spring">Spring</SelectItem>
            <SelectItem value="summer">Summer</SelectItem>
            <SelectItem value="autumn">Autumn</SelectItem>
            <SelectItem value="winter">Winter</SelectItem>
          </SelectContent>
        </Select>
        <Command className="flex-1">
          <CommandInput placeholder="Search pumpkins..." />
          <CommandList>
            <CommandEmpty>No pumpkins found.</CommandEmpty>
          </CommandList>
        </Command>
        <Button>Edit</Button>
        <Button>Analyze</Button>
        <Button>Compare</Button>
      </div>
      <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
        <Card className="bg-white">
          <CardHeader>
            <div className="flex justify-between">
              <CardTitle>1234 Demo Pumpkin</CardTitle>
              <MoreVerticalIcon className="text-gray-400" />
            </div>
            <CardDescription>This is a sample description</CardDescription>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-gray-600">Latest Weight: 178.56 lbs</p>
            <p className="text-sm text-gray-600">Days After Pollination: 99 days</p>
          </CardContent>
          <CardFooter className="flex justify-between">
            <Button variant="outline">Add Measurement</Button>
            <Button variant="ghost">Detailed View</Button>
          </CardFooter>
        </Card>
        <Card className="bg-white">
          <CardHeader>
            <div className="flex justify-between">
              <CardTitle>Backup Pumpkin</CardTitle>
              <MoreVerticalIcon className="text-gray-400" />
            </div>
            <CardDescription>This is another sample description</CardDescription>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-gray-600">Latest Weight: 33.10 lbs</p>
          </CardContent>
          <CardFooter className="flex justify-between">
            <Button variant="outline">Add Measurement</Button>
            <Button variant="ghost">Detailed View</Button>
          </CardFooter>
        </Card>
        <Card
          className="bg-white border-dashed border-2 border-gray-300 flex flex-col items-center justify-center p-6 text-center">
          <PlusIcon className="mb-2 text-gray-400" />
          <p className="text-lg font-medium">Add a new pumpkin</p>
        </Card>
      </div>
    </div>)
  );
}


function MoreVerticalIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="1" />
      <circle cx="12" cy="5" r="1" />
      <circle cx="12" cy="19" r="1" />
    </svg>)
  );
}


function PlusIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>)
  );
}
