/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/VEhmkUDBq5e
 */
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function herosearch() {
  return (
    (<div className="max-w-4xl mx-auto p-6">
      <h1 className="text-4xl font-bold text-center mb-4">GPC Search</h1>
      <p className="text-center text-lg mb-6">
        Find any grower, pumpkin, or site and get a comprehensive overview, rankings, and stats for each search result.
      </p>
      <div className="flex items-center border border-gray-300 rounded-md mb-8">
        <Input className="flex-1 p-4 border-0 rounded-l-md" placeholder="Search here..." />
        <MicroscopeIcon className="mr-4 text-gray-500" />
      </div>
      <div className="border border-gray-300 rounded-md">
        <div
          className="flex justify-between items-center p-4 border-b border-gray-300">
          <div>
            <h2 className="text-xl font-semibold">Gienger, Travis</h2>
            <p>Lifetime Max Weight: 2749 lbs</p>
            <p>Number Of Entries: 16</p>
          </div>
          <Button className="flex items-center gap-2 text-primary" variant="link">
            <span>View Details</span>
            <ArrowRightIcon className="w-5 h-5" />
          </Button>
        </div>
        <div
          className="flex justify-between items-center p-4 border-b border-gray-300">
          <div>
            <h2 className="text-xl font-semibold">Cutrupi, Stefano</h2>
            <p>Lifetime Max Weight: 2702.9 lbs</p>
            <p>Number Of Entries: 36</p>
          </div>
          <Button className="flex items-center gap-2 text-primary" variant="link">
            <span>View Details</span>
            <ArrowRightIcon className="w-5 h-5" />
          </Button>
        </div>
        <div className="flex justify-between items-center p-4">
          <div>
            <h2 className="text-xl font-semibold">Paton, Stuart And Ian</h2>
            <p>Lifetime Max Weight: 2656.1 lbs</p>
            <p>Number Of Entries: 40</p>
          </div>
          <Button className="flex items-center gap-2 text-primary" variant="link">
            <span>View Details</span>
            <ArrowRightIcon className="w-5 h-5" />
          </Button>
        </div>
      </div>
    </div>)
  );
}


function MicroscopeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M6 18h8" />
      <path d="M3 22h18" />
      <path d="M14 22a7 7 0 1 0 0-14h-1" />
      <path d="M9 14h2" />
      <path d="M9 12a2 2 0 0 1-2-2V6h6v4a2 2 0 0 1-2 2Z" />
      <path d="M12 6V3a1 1 0 0 0-1-1H9a1 1 0 0 0-1 1v3" />
    </svg>)
  );
}


function ArrowRightIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>)
  );
}
