/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/QBVoI1jfbCF
 */
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function register() {
  return (
    (<div className="min-h-screen flex">
      <div className="w-1/2 bg-gray-100 p-12">
        <CarrotIcon className="text-6xl" />
        <h1 className="mt-4 text-3xl font-semibold">PumpkinPal</h1>
        <p className="mt-6 text-lg">
          "This library has saved me countless hours of work and helped me deliver stunning designs to my clients faster
          than ever before."
        </p>
        <p className="mt-4 font-semibold">Sofia Davis</p>
      </div>
      <div className="w-1/2 flex flex-col justify-center p-12">
        <div className="flex justify-between items-center">
          <div />
          <Link className="text-sm" href="#">
            Login
          </Link>
        </div>
        <div className="mt-6">
          <h2 className="text-2xl font-bold">Create an account</h2>
          <p className="mt-2 text-sm">Enter your email below to create your account</p>
          <form className="mt-4">
            <Input className="mb-4" placeholder="name@example.com" type="email" />
            <Button className="w-full mb-2">Sign In with Email</Button>
            <div className="my-4 flex items-center justify-center">
              <div className="flex-grow border-t border-gray-300" />
              <span className="mx-4 text-sm text-gray-600">OR CONTINUE WITH</span>
              <div className="flex-grow border-t border-gray-300" />
            </div>
            <Button className="w-full mb-4" variant="outline">
              <FacebookIcon className="mr-2" />
              Facebook{"\n                  "}
            </Button>
            <Button className="w-full" variant="outline">
              <ChromeIcon className="mr-2" />
              Google{"\n                  "}
            </Button>
            <p className="mt-4 text-xs text-center">
              By clicking continue, you agree to our
              <Link className="text-blue-600" href="#">
                Terms of Service
              </Link>{" "}
              and{" "}
              <Link className="text-blue-600" href="#">
                Privacy Policy
              </Link>
              .{"\n                  "}
            </p>
          </form>
        </div>
      </div>
    </div>)
  );
}


function CarrotIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M2.27 21.7s9.87-3.5 12.73-6.36a4.5 4.5 0 0 0-6.36-6.37C5.77 11.84 2.27 21.7 2.27 21.7zM8.64 14l-2.05-2.04M15.34 15l-2.46-2.46" />
      <path d="M22 9s-1.33-2-3.5-2C16.86 7 15 9 15 9s1.33 2 3.5 2S22 9 22 9z" />
      <path d="M15 2s-2 1.33-2 3.5S15 9 15 9s2-1.84 2-3.5C17 3.33 15 2 15 2z" />
    </svg>)
  );
}


function FacebookIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>)
  );
}


function ChromeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="12" r="4" />
      <line x1="21.17" x2="12" y1="8" y2="8" />
      <line x1="3.95" x2="8.54" y1="6.06" y2="14" />
      <line x1="10.88" x2="15.46" y1="21.94" y2="14" />
    </svg>)
  );
}
